// Curated water-logy phrases for the Level 7 Face overlay.
// Pulled & condensed from the project manifesto, one phrase per "thought".
export const FACE_PHRASES: string[] = [
  'a comparative water-logy',
  'water as resource, molecule, spirit',
  'water as infrastructure, territory, memory',
  'water as health, danger, commodity, relation',
  'water as climate, data, archive, game',
  'each model produces different attention',
  'different institutions, different interfaces',
  'different intuitions, different forms of violence and care',
  'challenge the map mode of water',
  'a river becomes a line',
  'the sea becomes a polygon',
  'the ecosystem becomes a dataset',
  'crisis becomes something observed from above',
  'powerful and necessary — but ideological',
  'the environment is not clean, not external',
  'not separate from the bodies who live inside it',
  'do not reject maps — stress them, bend them, break them',
  'following Morton — refuse the data dump',
  'more graphs are not more awareness',
  'following Haraway — stay with the trouble',
  'situated making, partial perspectives',
  'play, shared responsibility',
  'following Bratton — anti-anti-totality',
  'a multiplicity of totalities',
  'geopolitics, irrigation, dams, cotton fields',
  'schoolyards, gestures and dreams in one frame',
  'make the serious playful',
  'make the playful serious',
  'big is small and small is big',
  'a dam is an engineering object',
  'a dam is a geopolitical interface',
  'a dam is a game mechanic',
  'a cotton field is a flower',
  'a cotton field is geotechnology',
  'a cotton field is terraforming',
  'a river is snow, labour, state planning',
  'a river is extraction, soil, salinity',
  'a river is memory, fish, children, canals, futures',
  'a child\u2019s gesture is small',
  'a small gesture can move a simulated sea',
  'the sea is enormous',
  'it can be held, played, broken, restored',
  'misunderstood, and reimagined',
  'play makes complexity graspable',
  'without pretending it has become simple',
  'turn the instrument toward its own limits',
  'expose the apparatus publicly, performatively',
  'not critique alone — interaction, play, speculation',
  'a mapping platform that is also a video game',
  'real data, playful interfaces, gesture control',
  'kids\u2019 agency and dreams',
  'experience the ecosystem',
  'do not only read about it',
  'for schools, museums, festivals, ministries',
  'from prototype to classroom',
  'from classroom to museum',
  'from museum to ministry',
  'from ministry back to children',
  'flood it, dry it, plant it, reroute it',
  'break it, restore it',
  'what models of water are we playing with',
  'when we imagine its past, present and future',
];
